"""create core dbms schema

Revision ID: 07d43590c27a
Revises: 
Create Date: 2026-09-11 08:23:52.175263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07d43590c27a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commitments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('FIXED_EVENT', 'RECURRING_QUOTA', 'FLEXIBLE_TASK', 'HARD_DEADLINE', name='commitmenttype'), nullable=False),
    sa.Column('target_per_week', sa.Integer(), nullable=True),
    sa.Column('duration_blocks', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('constraint_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('commitment_id', sa.String(length=36), nullable=False),
    sa.Column('rule_type', sa.Enum('TIME_OF_DAY_AFFINITY', 'SEPARATION', 'ENERGY_TIERING', name='ruletype'), nullable=False),
    sa.Column('target_slot', sa.Integer(), nullable=True),
    sa.Column('strictness', sa.Enum('HARD', 'SOFT', name='strictness'), nullable=False),
    sa.ForeignKeyConstraint(['commitment_id'], ['commitments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_blocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('commitment_id', sa.String(length=36), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='dayofweek'), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'COMPLETED', 'MISSED', 'SKIPPED', name='blockstatus'), nullable=False),
    sa.Column('actual_start', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['commitment_id'], ['commitments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('block_id', sa.String(length=36), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['scheduled_blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('execution_logs')
    op.drop_table('scheduled_blocks')
    op.drop_table('constraint_rules')
    op.drop_table('commitments')
    # ### end Alembic commands ###
